---
title: "10X Genomics analysis of ITP samples"
author: "David Schmidt, d.schmidt@sanquin.nl"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

CONCEPT

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F,message = F)
```

```{r libs}
library(tidyverse)
library(Seurat)
library(future)
library(cowplot)
library(knitr)
library(beepr)
library(magrittr)
library(ggsci)
theme_set(theme_cowplot())

```


## CD4 T cell subtypes in ITGB1 vs all CD4 

Load clustered T cells 

Viz Cells per cluster

```{r}
tCells = readRDS("data/processed/20200626 tCells_Clustered.rds")
table(tCells$seurat_clusters) %>% kable(caption="T cells per identified seurat cluster(all samples)")
```

```{r viz-tCell, fig.width=12,fig.height=4}
p1 = DimPlot(tCells, reduction = "umap",label = F)
# p1 + scale_color_lancet() # doens't look good 
p2 = DimPlot(tCells, reduction = "umap",label = F)  + theme(legend.position = "none")
p3 = DimPlot(tCells, reduction = "umap",label = T) + theme(legend.position = "none")
CombinePlots(plots = list(p1,p2,p3),ncol = 3)
rm(p1,p2,p3)
# save_plot(tikiR::figpath("tCells_clusters.pdf"),last_plot(),base_width=12,base_height=4)
# save_plot(tikiR::figpath("tCells_clusters_large.pdf"),last_plot(),base_width=15,base_height=5)
```

```{r viz-tCell-by-group}
DimPlot(tCells, reduction = "umap",label = F,split.by = "group")  + theme(legend.position = "none")
# save_plot(tikiR::figpath("tCells-Cluster-group-nolegend.pdf"),last_plot(),base_width=6,base_height=3)
DimPlot(tCells, reduction = "umap",label = F,split.by = "orig.ident",ncol=3) + theme(legend.position = "none")
# save_plot(tikiR::figpath("tCells-Cluster-pid-nolegend.pdf"),last_plot(),base_width=9,base_height=6)
```

Define cluster identity

```{r}
# gather extra data to distinguish similar clusters pairwise
markers.to.plot <- c("CD3D", "IL7R", "CCR7", "GZMA","CD8A","CD8B","CXCR3","GZMK","KLRD1","XCL1","KLRF1","EOMES","CX3CR1",
                     "CD4","FOXP3","CTLA4","IL2RA","CXCR6","KLRB1")

DefaultAssay(tCells) <- "RNA"
DotPlot(tCells, features = rev(markers.to.plot),
        cols = c("white", "#de2d26"),
        dot.scale = 5) + RotatedAxis()
DefaultAssay(tCells) <- "integrated"
rm(markers.to.plot)
```

```{r include=F,eval=F}
# targeted details by pairwise comparison

compareIdents = function(object, ident1,ident2,annotation){
    # Find markers that are conserved between the groups for cell identity 1 compared to cell identity 2
    conserved.markers = FindConservedMarkers(object,ident1,ident2,grouping.var = "group") 
    conserved.markers$gene = rownames(conserved.markers)
    
    # conserved.markers %<>%
      # filter(max_pval < 0.05)
    
    # Select 'avg_logFC' columns indices
    avg_logFC_columns <- grep(pattern = "avg_logFC", x = colnames(x = conserved.markers))
    
    # Compute mean 'avg_logFC'
    conserved.markers$mean_avg_logFC <- rowMeans(x = conserved.markers[avg_logFC_columns])
    
    ## For upregulated genes
    # Order 'conserved.markers' by 'mean_avg_logFC'
    conserved.markers <- conserved.markers[order(conserved.markers$mean_avg_logFC, decreasing = TRUE), ]
    
    # Get top 10 genes
    up = rownames(x = conserved.markers[1:10,])
    
    ## For downregulated genes
    # Order 'conserved.markers' by 'mean_avg_logFC'
    conserved.markers <- conserved.markers[order(conserved.markers$mean_avg_logFC, decreasing = FALSE), ]
    
    # Get top 10 genes
    down = rownames(x = conserved.markers[1:10,])
    
    out = conserved.markers %>% 
      filter(gene %in% up | gene %in% down) %>% 
      mutate(ident.1 = ident1, 
             ident.2 = ident2) %>%
      select(gene, ident.1,ident.2, mean_avg_logFC,max_pval) %>%
      arrange(desc(mean_avg_logFC))
    
    # log the output
    write.csv2(out,paste0("data/output/conservedMarkers_",annotation,"_ident",ident1,"_vs",ident2,".csv"))
    print(paste0("wrote results to data/output/conservedMarkers_",annotation,"_ident",ident1,"_vs",ident2,".csv"))
    
    return(out)
}
```

#### Analyze expression 

```{r}
# avgExp = AverageExpression(tCells)
# head(avgExp[["RNA"]])

# Idents(tCells)
# Idents(tCells) = paste("cluster",Idents(tCells),sep="")

avgExp <- AverageExpression(tCells, return.seurat = TRUE)
avgExp$orig.ident


# selected T cell  features
# DefaultAssay(avgExp) = "integrated"
# DefaultAssay(avgExp) = "RNA"
# avgExp = ScaleData(avgExp)
genes =  c("CCR7","SELL","LDHB","LRRN3",  #naive, our data (PCA)
           "FHIT","TCF7", "FCGRT",
           "JUN","JUNB", "FOS", "CD69", # early activation
           "CD8A","CTSW",
           "NKG7","CST7", "CCL5","KLRD1","GZMH","PRF1", "FCGR3A", #CD8
           "ZNF683","ITGB1", "S100A4","ANXA1","KLF6","LGALS3","CYTOR", #activ
           "FOXP3","IL2RA","TIGIT","CTLA4","IL32", "PLCL1","SHMT2","C21orf91" #Treg by Cuadrado Immunity 2018
        )

DoHeatmap(avgExp, features = genes, size = 3, 
    draw.lines = F,raster = FALSE,group.bar = T)
# save_plot(tikiR::figpath("tCells_heatMap_Cannonical.pdf"),last_plot(),base_width =5,base_height=6)
```

```{r}
genes = c("CD8A","CCL5", "CCR7","ITGB1",
          "IL2RA","CTLA4")

FeaturePlot(tCells,features=genes,min.cutoff = "q20")
```

#### Calculate proportions

```{r}
tCells.list = data.frame(cluster = tCells$seurat_clusters, group = tCells$group,pid = tCells$orig.ident)
tCells.list$cellID = rownames(tCells.list)

tCells.list %<>%
  mutate(group = group %>% fct_relevel("transient","chronic"))

# calculate proportion of cells in each cluster per patient
proportions = tCells.list %>%
  add_count(pid,name = "N") %>%
  count(pid,cluster,N) %>%
  mutate(proportion=n/N)   

# add group data
proportions %<>% 
  left_join(tCells.list %>% count(pid,group) %>% select(pid,group),# fix to quickly access group data
             by="pid")

# proportions %<>%
  # left_join(clusters %>% mutate(cluster = cluster %>% as.character))


```

Display CCR7+ vs negative  CD4 

```{r}
subtypes = proportions %>%
  select(-proportion) %>%
  filter(!(cluster %in% c("2","10", "7","9","6")))%>%
  mutate(CCR7 = case_when(
    cluster %in% c("3","8") ~ "CCR7-",
    TRUE ~ "CCR7+"
  )) %>%
  group_by(pid,N,CCR7) %>%
  summarise(sum_type = sum(n)) %>%
  group_by(pid)%>%
  mutate(N=sum(sum_type)) %>%
  # rename(sum_type = n) %>%
  mutate(proportion=sum_type/N)  

subtypes %>%
  group_by(pid)%>%
  mutate(N=sum(sum_type))

# add group data
subtypes %<>% 
  left_join(tCells.list %>% count(pid,group) %>% select(pid,group),# fix to quickly access group data
             by="pid")

subtypes %>%
  ggplot(aes(group,proportion,col=group)) +
  stat_summary(geom="errorbar",width=0.2) +
  stat_summary(geom="point") +
  geom_point(alpha=0.5) +
  facet_wrap(~CCR7,scales = "free_x",ncol=5)+
              # labeller = labeller(cluster = clusterLabels)) +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "top",
        legend.title = element_blank()) +
  xlab("") +
  scale_color_lancet()

# save_plot(tikiR::figpath("proportions_CCR7_CD4.pdf"),last_plot() + theme(legend.position = "none"),base_width=6,base_height=3)
```

#### Try to define Treg as a cluster subset


```{r}
# get tReg signature genes
counts = tCells@assays[["RNA"]]@counts 
TregSignature = counts[c("FOXP3","CTLA4","IL32","TIGIT","IL2RA"),] %>% as.matrix %>% t() 

# run PCA for treg signature
pc = prcomp(TregSignature,scale=TRUE)
TregSignatureScore = pc$x[,1] # PC1

library(ggfortify)
autoplot(pc,loadings = TRUE,loadings.label = TRUE)

tCells@meta.data$TregSignatureScore = TregSignatureScore
# save_plot(tikiR::figpath("TregSignatureScore_Loadings.pdf"),last_plot(),base_width = 3,base_height=3)


# small edits
tCells@meta.data$Treg = TregSignatureScore > 5
tCells@meta.data$Treg = tCells@meta.data$Treg %>% as_factor() %>%
  fct_recode("Treg"= "TRUE","otherT" = "FALSE") %>%
  fct_relevel("Treg","otherT")
```


```{r}
# pdf(tikiR::figpath("TregSignatureScore.pdf"),width = 3,height=3)
# boxplot(TregSignatureScore)
# dev.off()

tCells@meta.data %>%
  ggplot(aes(seurat_clusters,TregSignatureScore,fill=seurat_clusters)) +
  geom_violin() +
  theme(legend.position="none") 

# save_plot(tikiR::figpath("TregSignatureScore_Cluster.pdf"),last_plot(),base_width = 6,base_height=3)
```

```{r}
tCells@meta.data$Treg %>% table

Idents(tCells) = "Treg"
DimPlot(tCells) +
  scale_color_manual(values=c("darkblue","lightgrey")) +
  theme(legend.position = "none",axis.ticks = element_blank(),
        axis.text = element_blank()) +
  labs(x="",y="")

# save_plot(tikiR::figpath("TregSignatureScore_DimPlot.pdf"),last_plot(),base_width = 3,base_height=3)

```

```{r}
tReg = subset(tCells, subset = seurat_clusters %in% c(3,8) )
```
